// Code generated by candi v1.16.3.

package shared

import "time"

// Environment additional in this service
type Environment struct {
	// more additional environment with struct tag is environment key example:
	// ExampleHost string `env:"EXAMPLE_HOST"`
	TokenEncryptionKey string `env:"TOKEN_ENCRYPTION_KEY"`
	TokenEncryption    bool   `env:"TOKEN_ENCRYPTION"`

	JWTRefreshTokenAge  time.Duration `env:"JWT_REFRESH_TOKEN_AGE"`
	JWTAccessTokenAge   time.Duration `env:"JWT_ACCESS_TOKEN_AGE"`
	JWTRegisterTokenAge time.Duration `env:"JWT_REGISTER_TOKEN_AGE"`

	EmailSenderNoReply string `env:"EMAIL_SENDER_NO_REPLY"`
	MailgunDomain      string `env:"MAILGUN_DOMAIN"`
	MailgunPrivateKey  string `env:"MAILGUN_PRIVATE_KEY"`

	SMTPHost     string `env:"SMTP_HOST"`
	SMTPPort     int    `env:"SMTP_PORT"`
	SMTPUsername string `env:"SMTP_USERNAME"`
	SMTPPassword string `env:"SMTP_PASSWORD"`

	WebsiteURL string `env:"WEBSITE_URL"`
	BaseURL    string `env:"BASE_URL"`
}

var sharedEnv Environment

// GetEnv get global additional environment
func GetEnv() Environment {
	return sharedEnv
}

// SetEnv get global additional environment
func SetEnv(env Environment) {
	sharedEnv = env
}
