// Code generated by candi v1.16.3.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	complaintusecase "service-complaint/internal/modules/complaint/usecase"
	userusecase "service-complaint/internal/modules/user/usecase"
	"service-complaint/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		User() userusecase.UserUsecase
		Complaint() complaintusecase.ComplaintUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		userusecase.UserUsecase
		complaintusecase.ComplaintUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.UserUsecase, setSharedUsecaseFunc = userusecase.NewUserUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.ComplaintUsecase, setSharedUsecaseFunc = complaintusecase.NewComplaintUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) User() userusecase.UserUsecase {
	return uc.UserUsecase
}

func (uc *usecaseUow) Complaint() complaintusecase.ComplaintUsecase {
	return uc.ComplaintUsecase
}
