// Code generated by candi v1.16.3.

package repository

import (
	"context"

	"service-auth/internal/modules/notification/domain"
	shareddomain "service-auth/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// NotificationRepository abstract interface
type NotificationRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterNotification) ([]shareddomain.Notification, error)
	Count(ctx context.Context, filter *domain.FilterNotification) int
	Find(ctx context.Context, filter *domain.FilterNotification) (shareddomain.Notification, error)
	Save(ctx context.Context, data *shareddomain.Notification, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterNotification) (err error)
}
