// Code generated by candi v1.16.3.

package repository

import (
	"context"

	"strings"
	"time"

	"service-auth/internal/modules/notification/domain"
	shareddomain "service-auth/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"service-auth/pkg/shared"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type notificationRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewNotificationRepoSQL mongo repo constructor
func NewNotificationRepoSQL(readDB, writeDB *gorm.DB) NotificationRepository {
	return &notificationRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *notificationRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterNotification) (data []shareddomain.Notification, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "NotificationRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "created_at"
	}

	db := r.setFilterNotification(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *notificationRepoSQL) Count(ctx context.Context, filter *domain.FilterNotification) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "NotificationRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterNotification(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Notification{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *notificationRepoSQL) Find(ctx context.Context, filter *domain.FilterNotification) (result shareddomain.Notification, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "NotificationRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterNotification(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *notificationRepoSQL) Save(ctx context.Context, data *shareddomain.Notification, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "NotificationRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = shared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = shared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *notificationRepoSQL) Delete(ctx context.Context, filter *domain.FilterNotification) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "NotificationRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterNotification(shared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.Notification{}).Error
	return
}

func (r *notificationRepoSQL) setFilterNotification(db *gorm.DB, filter *domain.FilterNotification) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}

	if filter.UserID != 0 {
		db = db.Where("user_id = ?", filter.UserID)
	}

	if len(filter.IDs) > 0 {
		db = db.Where("id IN ?", filter.IDs)
	}

	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	if filter.IsRead != nil {
		db = db.Where("is_read = ?", filter.IsRead)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
