// Code generated by candi v1.16.3.

package shared

import "time"

// Environment additional in this service
type Environment struct {
	// more additional environment with struct tag is environment key example:
	// ExampleHost string `env:"EXAMPLE_HOST"`
	TokenEncryptionKey string `env:"TOKEN_ENCRYPTION_KEY"`
	TokenEncryption    bool   `env:"TOKEN_ENCRYPTION"`

	ServiceAuthHost string `env:"SERVICE_AUTH_HOST"`
	ServiceAuthKey  string `env:"SERVICE_AUTH_KEY"`

	ComplaintOpenAge time.Duration `env:"COMPLAINT_OPEN_AGE"`
	BaseURL          string        `env:"BASE_URL"`
}

var sharedEnv Environment

// GetEnv get global additional environment
func GetEnv() Environment {
	return sharedEnv
}

// SetEnv get global additional environment
func SetEnv(env Environment) {
	sharedEnv = env
}
